language: python
python:
   "2.7.15"
env:
  - APP_SETTINGS=testing
  - DB_URL1=postgresql://postgres:#kafuuma#@localhost/testffood
install:
  - "pip install -r requirements.txt"

before_script:
  - psql -c 'create database testffood;' -U postgres
script:
  - nosetests --with-coverage 
after_success:
  - "coveralls"
